site_name: Gon Docs
site_url: https://gonkun.github.io
site_author: Gon
site_description: My personal documentation because I'm a disaster

nav:
  - Home: index.md
  - User Guide:
    - Kubernetes:
      - k8s.md
      - cka_tips.md
    - DataStax: dse.md
    - Terraform: terraform.md
    - AWS: aws.md
    - Istio: istio.md
    - BASH: bash.md
    - GitHub Actions: github-actions.md
    - AI for DevOps: ai-for-devops.md
    - Networking: networking.md
    - Others: others.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml